import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';

const CACHE_ID = 'text0wnz-shared-files';
const CACHE_DATA = '/shared-file-data';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Handle share target POST requests
self.addEventListener('fetch', event => {
	const url = new URL(event.request.url);
	if (url.pathname === '/open' && event.request.method === 'POST') {
		event.respondWith(handleShareTarget(event.request));
	}
});

async function handleShareTarget(request) {
	try {
		const formData = await request.formData();
		const file = formData.get('file');

		if (file && file.size > 0) {
			const cache = await caches.open(CACHE_ID);
			await cache.put(
				new Request(CACHE_DATA),
				new Response(file, {
					headers: {
						'Content-Type': file.type || 'application/octet-stream',
						'X-Filename': file.name || 'untitled.txt',
						'X-File-Size': file.size.toString(),
						'X-Shared-At': Date.now().toString(),
						'X-Source': 'share-target',
					},
				}),
			);
			const clients = await self.clients.matchAll({ type: 'window' });
			clients.forEach(client => {
				client.postMessage({
					type: 'SHARED_FILE_READY',
					filename: file.name,
					size: file.size,
				});
			});
		}
		return Response.redirect('/?source=share', 303);
	} catch (error) {
		console.error('[ServiceWorker] Error handling share target:', error);
		return Response.redirect('/', 303);
	}
}

// Regex safe UI directory from build environment
const uiDir = (import.meta.env.VITE_UI_DIR || 'ui/')
	.slice(0, -1)
	.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// Runtime caching strategies
registerRoute(
	({ url }) =>
		url.pathname.match(new RegExp(`^\\/${uiDir}\\/img\\/.*\\.(png|svg|ico)$`)),
	new CacheFirst({ cacheName: 'asset-cache' }),
);
registerRoute(
	({ url }) => url.pathname.match(new RegExp(`^\\/${uiDir}\\/js\\/.*\\.js$`)),
	new CacheFirst({ cacheName: 'app-cache' }),
);
registerRoute(
	({ url }) =>
		url.pathname.match(new RegExp(`^\\/${uiDir}\\/.*\\.(css|svg|woff2)$`)),
	new CacheFirst({ cacheName: 'style-cache' }),
);
registerRoute(
	({ url }) => url.pathname === '/' || url.pathname === '/index.html',
	new CacheFirst({ cacheName: 'html-cache' }),
);

// Clean up old files on activation
self.addEventListener('activate', event => {
	event.waitUntil(
		(async () => {
			try {
				const cache = await caches.open(CACHE_ID);
				const keys = await cache.keys();
				if (keys.length > 0) {
					console.log(
						`[ServiceWorker] Found ${keys.length} stale shared file(s), clearing cache`,
					);
					await caches.delete(CACHE_ID);
				}
			} catch (error) {
				console.error(
					'[ServiceWorker] Failed to cleanup shared file cache:',
					error,
				);
			}
		})(),
	);
});
