name: Deploy Coverage Reports
on:
  workflow_call:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy-coverage:
    runs-on: ubuntu-latest
    name: Deploy Coverage Reports to GitHub Pages
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: unit-test-results
      - name: Download build artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: playwright-report
      - name: Organize test results
        run: |
          mkdir -p test-results/unit
          mkdir -p test-results/e2e
          cp -r unit-test-results/* test-results/unit/ || true
          cp -r playwright-report/* test-results/e2e/ || true
      - name: Deploy coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: test-results
          destination_dir: test-results
          publish_branch: gh-pages
