name: Deploy Coverage Reports

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-coverage:
    runs-on: ubuntu-latest
    name: Deploy Coverage Reports to GitHub Pages
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22.19"
          cache: 'npm'

      - name: Install Bun
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun i

      - name: Generate coverage reports
        run: bun test:unit

      - name: Copy coverage reports
        run: |
          mkdir -p public/coverage
          cp -r tests/results/coverage/* public/coverage/ || true

      - name: Inject dark theme into coverage report
        run: |
          echo "@media (prefers-color-scheme:dark){.cover-empty,body{background:#000}body{color:#efefef}table{color:#000}table,td,th{border:1px solid #222!important}td.empty{color:#eee}.cbranch-no,.cstat-no,.fstat-no{background:#afe9dc}.cline-yes,.high{background:#f2bfff}.cline-no,.low{background:#bbf2e8}.fraction,.quiet,table .chart,table .high,table .low,td.text,th.file,th.pct{-webkit-filter:invert(100%)}.footer{display:none!important}body>div.wrapper>div:first-child>p{background:#ddd;width:fit-content;padding:10px}}" >> public/coverage/base.css

      - name: Deploy coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/coverage
          destination_dir: coverage
          publish_branch: gh-pages
