name: Deploy to GitHub Pages
on:
  workflow_call:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  get-artifacts:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: get-artifacts
    steps:
      - name: download build artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: editor-build
          path: dist
      - name: download unit artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: unit-test-results
          path: unit
      - name: download e2e artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: playwright-report
          path: e2e
      - name: organize
        run: |
          mkdir release
          cp -r dist/* release
          mkdir dist/tests
          cp -r unit/* dist/tests
          mkdir dists/tests/e2e
          cp e2e/index.html dist/tests/e2e
      - name: upload release build artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: github-pages
          path: release
          retention-days: 3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: get-artifacts
    name: deploy editor
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: deploy editor
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
        with:
          artifact_name: github-pages

