name: merge playwright reports
on:
  workflow_call:
    inputs:
      retention-days:
        required: false
        type: number
        default: 14
permissions:
  contents: read
jobs:
  merge-reports:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: install bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: 'latest'
      - name: install playwright
        run: bunx playwright install
      - name: download blob reports
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true
      - name: merge report
        run: bunx playwright merge-reports --reporter html ./all-blob-reports
      - name: upload merged report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: merged-playwright-report
          path: playwright-report
          retention-days: ${{ inputs.retention-days }}
