name: test suite
on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
  packages: read
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  build:
    uses: ./.github/workflows/build.yml
  unit:
    uses: ./.github/workflows/unit.yml
  e2e:
    uses: ./.github/workflows/e2e.yml
  deploy:
    needs: [lint, unit, build, e2e]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
