name: test suite
on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
  packages: read
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  build:
    uses: ./.github/workflows/build.yml
  unit:
    uses: ./.github/workflows/unit.yml
  e2e:
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    uses: ./.github/workflows/e2e.yml
    with:
      shard: ${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
  reports:
    if: ${{ !cancelled() }}
    needs: [e2e]
    uses: ./.github/workflows/merge-reports.yml
  deploy:
    needs: [lint, unit, build, reports]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
