name: Minimal Deploy Test
on:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create minimal site
        run: |
          mkdir site
          echo '<html><body><h1>Hello World</h1></body></html>' > site/index.html
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: github-pages
          path: site
      - name: Deploy
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
        with:
          artifact_name: github-pages
