name: Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  unit:
    uses: ./.github/workflows/unit.yml

  build:
    uses: ./.github/workflows/build.yml

  e2e:
    uses: ./.github/workflows/e2e.yml

  commit-results:
    needs: [lint, unit, build, e2e]
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    uses: ./.github/workflows/commit-results.yml

  deploy:
    needs: commit-results
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    uses: ./.github/workflows/deploy-pages.yml
